### ISSUE TITLE
"nb==3" or "nb!=3" in Improper setting

### ISSUE THREAD

**Issue by ghost** [CMMRLab/LUNAR#1]
Dear @jdkemppa 
Thanks for the great program.
I have a question.
What does “nb==3” or “nb!=3” mean that appears in the Improper related section after running all2lmp.py?
Best regards,

**Comment by jdkemppa** [comment]
Hello,

Thank you for the compliment. In my shorthand, nb stands for "number of bond atoms to the central atom." I added these additional comments to keep a few things from getting mixed up due to how LAMMPS handles "Improper Coeffs" and "Angle Angle Coeffs." Basically, LAMMPS has you put both of those coeff types in the same section, even though they are technically different interactions. An Improper has 3 bonded neighbors (so any parameters with the "nb==3" implies that is an Improper coeff) and an AngleAngle typically has 4 bonded neighbors (so any parameters with the "nb!=3" implies that is an AngleAngle coeff).

Those additional comments were added so that LUNAR/bond_react_merge and LUNAR/cell_builder can merge the Impropers and AngleAngle coeffs without possibly mixing up either interaction type. If you open up the *.txt comment file from LUNAR/all2lmp, there are additional comments about the differences between "nb==3" and "nb!=3". AngleAngle coeffs are only present in class2 force fields so for class2 force fields you will see both "nb==3" and "nb!=3". Then typically for class1 force fields, there will only be "nb==3" as they only consider improper interactions (there are more advanced class1 force fields that model crossterms, but LAMMPS potentials do not currently support that, so I have not coded LUNAR to support such class1 type of force fields yet).

Thanks,
Josh
